# Generated by Django 2.1.2 on 2020-02-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='shop/images')),
            ],
        ),
    ]
