# Generated by Django 2.1.2 on 2020-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(default='', max_length=500),
        ),
    ]
