# Generated by Django 2.1.2 on 2020-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(default=True, max_length=5000),
        ),
    ]
